---
name: Lint Docs
on:
  # Trigger the workflow on push or pull request, but only for the gh-pages branch
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
jobs:
  docs-lint:
    name: Markdownlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: '.' # From https://github.com/github/super-linter/pull/859#issuecomment-709625090

          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: ./.markdownlint.yml
          FILTER_REGEX_INCLUDE: '/.*'
